// 'Group 21 - COMP90024 Cluster and Cloud Computing'

var suburbs = {
	'Ang Mo Kio':0,
	'Bedok':0,
	'Bishan':0,
	'Boon Lay':0,
	'Bukit Batok':0,
	'Bukit Mera':0,
	'Bukit Panjang':0,
	'Bukit Timah':0,
	'Central Water Catchment':0,
	'Changi':0,
	'Changi Bay':0,
	'Choa Chu Kang':0,
	'Clementi':0,
	'Downtown Core':0,
	'Geylang':0,
	'Hougang':0,
	'Jurong East':0,
	'Jurong West':0,
	'Kallang':0,
	'Lim Chu Kang':0,
	'Mandai':0,
	'Marina East':0,
	'Marina South':0,
	'Marine Parade':0,
	'Museum':0,
	'Newton':0,
	'North Eastern Islands':0,
	'Novena':0,
	'Orchard':0,
	'Outram':0,
	'Pasir Ris':0,
	'Paya Lebar':0,
	'Pioneer':0,
	'Punggol':0,
	'Queenstown':0,
	'River Valley':0,
	'Rochor':0,
	'Seletar':0,
	'Sembawang':0,
	'Sengkang':0,
	'Serangoon':0,
	'Simpang':0,
	'Singapore River':0,
	'Southern Islands':0,
	'Straits View':0,
	'Sungei Kadut':0,
	'Tampines':0,
	'Tanglin':0,
	'Tengah':0,
	'Toa Payoh':0,
	'Tuas':0,
	'Western Islands':0,
	'Western Water Catchment':0,
	'Woodlands':0,
	'Yishun':0
};

exports.region = suburbs;